### ISSUE TITLE
Add the list of contributors in the readme.md file

### ISSUE THREAD

**Issue by sumanthst24** [alexa-dev-hub/alexa-community-jaipur#15]
List out all the contributors to this repository and auto-add all the contributors
Go through this https://github.com/all-contributors/all-contributors for more information

**Comment by Tushar11Raj** [comment]
Can I do this?

**Comment by hariom1625** [comment]
Hey, I can help you in implementing this once you assign it to me but before that, i will need to know you want this to be added using ```npm package``` or ```all-contributors bot``` can add using both.

**Comment by tarunnsingh** [comment]
@hariom1625 We would encourage you to use npm package.
We need that list to be in the README, so it's upto you whatever you would like to use. 
Shall I assign you on this?

**Comment by hariom1625** [comment]
Yeah sure :-)
But before starting I need you to know that this package doesn't automatically add the new contributors to the list, 
for updating, there are two ways one using CLI and other using Bot, So from my experience what I would suggest is that to configure the package using CLI in order to add the contributors who have already contributed till now and after that enabling the Bot to keep updating the Contributors list. I will share the details on how to configure the bot once I configure the files it is just quite a few steps and you are good to go :-)

**Comment by tarunnsingh** [comment]
Alright! That sounds good. Waiting for the Details.
Assigned.

**Comment by tarunnsingh** [comment]
Hey @Tushar11Raj What approach did you for this issue?

**Comment by hariom1625** [comment]
> Alright! That sounds good. Waiting for the Details.
> Assigned.

Since this issue is labeled under the Hactoberfest I will make the PR once the event starts :-)

**Comment by tarunnsingh** [comment]
Okay Cool!

**Comment by Tushar11Raj** [comment]
> Hey @Tushar11Raj What approach did you for this issue?

I will be using allcontributors bot for this. You will have to comment ont the pull request in the following way:
`@all-contributors please add <username> for <contributions>`
but this will also work:
`Jane you are crushing it in documentation and your infrastructure work has been great too. Let's add jane.doe23 for her contributions. cc @all-contributors`

**Comment by tarunnsingh** [comment]
I got your point @Tushar11Raj . Since I've already assigned it, and a similar workout would be done, you can keep track of this issue and make any suggestions or changes once PRs are merged.
