### ISSUE TITLE
Create/Design a LOGO

### ISSUE THREAD

**Issue by tarunnsingh** [alexa-dev-hub/alexa-community-jaipur#19]
### Current Website Heading is a Simple/Boring Text 🔽 
![image](https://user-images.githubusercontent.com/31896659/94781331-4bdc7580-03e7-11eb-86f4-46ab21e3390e.png)

**Comment by TheGiraffe** [comment]
Could I try this one?

**Comment by tarunnsingh** [comment]
Hey @TheGiraffe Would you be implementing the logo on the website or will add a separate logo file?

**Comment by TheGiraffe** [comment]
Will be a separate logo file, or maybe even a link on CodePen first so that you can take a look at it and see if it is good.

**Comment by tarunnsingh** [comment]
Perfect! Shall I assign you?

**Comment by TheGiraffe** [comment]
Yes, please! Thank you :)

**Comment by ManojAthreya** [comment]
Hey @tarunnsingh  can I try on this

**Comment by tarunnsingh** [comment]
Sure, @ManojAthreya give it a try.

**Comment by lakshit123456789** [comment]
i want to do work with you please tell me i am interested 
reply me if you want my help

**Comment by tarunnsingh** [comment]
> Yes, please! Thank you :)

@TheGiraffe are you working on this?

**Comment by tarunnsingh** [comment]
> i want to do work with you please tell me i am interested
> reply me if you want my help

Already two people assigned on this.

**Comment by TheGiraffe** [comment]
Not sure if this is still useful, however, if you are still looking for an animated logo...

What do you think of this?
https://codepen.io/sophiarobots/pen/LYNwLZm

Sorry for the delay in getting back to you, I am based in Hawai'i so I am always behind in terms of time zone. 😬

**Comment by tarunnsingh** [comment]
> Not sure if this is still useful, however, if you are still looking for an animated logo...
> 
> What do you think of this?
> https://codepen.io/sophiarobots/pen/LYNwLZm
> 
> Sorry for the delay in getting back to you, I am based in Hawai'i so I am always behind in terms of time zone. 😬

Hey @TheGiraffe This is so Cool! 😄 
No issue, with being a bit late.

Just a small update, could you please render this in **'Amazon Ember Regular'** font which is the official **Amazon Alexa Font**. You can find it [here](https://www.onlinewebfonts.com/download/02fcddff61b677f4989d2933d574ca89) or anywhere else. Keep it in all lowercase. With these changes, something like this ⏬  would work out, and shall look awesome on the site.
![image](https://user-images.githubusercontent.com/31896659/95000040-fd8fc800-05da-11eb-959f-a7a61e328f8e.png)

**Comment by TheGiraffe** [comment]
Link above should be updated with the new font, it looks like it loaded properly. I believe the link you sent me was for the Bold version of the font, which looked like this when I added it:
<img width="795" alt="Screen Shot 2020-10-03 at 9 46 00 AM" src="https://user-images.githubusercontent.com/4595588/95000549-80723d80-055d-11eb-8b7c-a17df943e909.png">
But then I searched around for the regular version and it looks like this:
<img width="776" alt="Screen Shot 2020-10-03 at 9 47 07 AM" src="https://user-images.githubusercontent.com/4595588/95000553-8ec05980-055d-11eb-9b12-0846c3edb2dd.png">

I put the regular version on the CodePen because I figured that this one was the preferred one, as it looks like your screenshot above. But totally cool with changing it to the bold one if that's preferred.

**Comment by tarunnsingh** [comment]
Please keep the Regular font and not the bold one.

**Comment by TheGiraffe** [comment]
https://codepen.io/sophiarobots/pen/LYNwLZm

Regular font should be live on the CodePen. :)

**Comment by tarunnsingh** [comment]
> https://codepen.io/sophiarobots/pen/LYNwLZm
> 
> Regular font should be live on the CodePen. :)

### Awesome 💯!
We would be utilizing your code-pen link to integrate it on the website. Please make sure you don't put that link down.
Thanks @TheGiraffe !!

**Comment by tarunnsingh** [comment]
@all-contributors please add @TheGiraffe for design

**Comment by TheGiraffe** [comment]
I'll definitely keep the CodePen link up, though as promised I also have an HTML file for the animation that I generated as well - with the sass compiled into regular css, plus some other formats (.gif .mov .mp4) of the animation included in the folder if useful. One of the benefits of the file version I made is that the font loads a lot better than the CodePen version, because the font is local rather than going through onlinewebfonts which seemed to make it load very slowly. I can fork the repo and add the folder to it then make a pull request if it would be useful for you.

**Comment by tarunnsingh** [comment]
> I'll definitely keep the CodePen link up, though as promised I also have an HTML file for the animation that I generated as well - with the sass compiled into regular css, plus some other formats (.gif .mov .mp4) of the animation included in the folder if useful. One of the benefits of the file version I made is that the font loads a lot better than the CodePen version, because the font is local rather than going through onlinewebfonts which seemed to make it load very slowly. I can fork the repo and add the folder to it then make a pull request if it would be useful for you.

That would actually be pretty useful, as you can see we have deployed your logo live. And mostly that lag is seen while loading. Please add your files in **alexa-community-jaipur/client/src/static/logo** and make a PR.
Thanks!

**Comment by tarunnsingh** [comment]
> i want to do work with you please tell me i am interested
> reply me if you want my help

Hey @lakshit123456789 , Sorry I missed out this message. As this task was already assigned, would you like to work on a similar issue. Let me know here. 😄
